import baseConfig from '../../../eslint.config.mjs';

export default [
  ...baseConfig,
  {
    files: ['**/*.json'],
    rules: {
      '@nx/dependency-checks': [
        'error',
        {
          ignoredFiles: [
            '{projectRoot}/eslint.config.{js,cjs,mjs,ts,cts,mts}',
            '{projectRoot}/vite.config.{js,ts,mjs,mts}',
          ],
          // `contentful` is imported only by the auto-generated types (type-only)
          // and provided as a root devDependency — don't require it in this
          // package's own dependencies.
          ignoredDependencies: ['contentful'],
        },
      ],
    },
    languageOptions: {
      parser: await import('jsonc-eslint-parser'),
    },
  },
  {
    // Auto-generated by cf-content-types-generator — not hand-maintained.
    ignores: ['**/out-tsc', 'src/lib/generated/**'],
  },
];
